on:
  pull_request:

name: Build firmware

jobs:
  changes:
    name: Detect changes to keyboards
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: read
    outputs:
      keyboards: ${{steps.filter.outputs.changes}}
    steps:
      - uses: actions/checkout@v3
      - name: Detect which keyboard had changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            keyboards/planck/rev7/keymaps/soryn:
                - 'keyboards/planck/rev7/keymaps/soryn/**'
            keyboards/0xcb/splaytoraid/keymaps/soryn:
                - 'keyboards/0xcb/splaytoraid/keymaps/soryn/**'

  build_firmware:
    name: ${{matrix.keyboard}}
    needs: changes
    if: ${{needs.changes.outputs.keyboards != '[]' && needs.changes.outputs.keyboards != ''}}
    strategy:
      matrix:
        keyboard: ${{ fromJSON(needs.changes.outputs.keyboards) }}
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Split changes keyboard string
        uses: xom9ikk/split@v1
        id: split
        with:
          string: ${{matrix.keyboard}}
          separator: /
          limit: -1
      - name: Build firmware
        uses: Soryyyn/qmk-build@v1.2
        with:
          keymap-path: "${{matrix.keyboard}}"
          keyboard: "${{ steps.split.outputs._1 }}/${{ steps.split.outputs._2}}"
          keymap: "${{ steps.split.outputs._4}}"
      - name: Move firmware to folder
        run: |
          cp ./build/*.hex ./build/*.bin ./build/*.uf2 ./firmware
      - name: Upload firmware to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: "./firmware"
          message: "chore(firmware): Upload newest firmware for ${{matrix.keyboard}}"
          pathspec_error_handling: exitAtEnd
          default_author: github_actions
